### ISSUE TITLE
Review PDF says it is a draft document

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#208] opened 2016-04-22 21:19 UTC
Review page 
The PDF says it is a draft document.

**Comment by jehlers** [comment] 2016-04-25 14:56
What about a header like this?

![screen shot 2016-04-25 at 10 55 29 am](https://cloud.githubusercontent.com/assets/4267825/14788073/4de8c6be-0ad4-11e6-8fe7-0c6178b76b0c.png)

**Comment by vrajmohan** [comment] 2016-04-25 17:43
This is definitely a duplicate of eregs/notice-and-comment#124.

**Closed by vrajmohan** 2016-04-25 17:43 UTC
Labels: High Priority, Review page
